### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Jhnbrn90** [writingink/wink#1]
Can we have a contributing.md on how to contribute to the package?

**Comment by themsaid** [comment]
here: https://github.com/writingink/wink/blob/master/CONTRIBUTING.md

**Comment by hilmanski** [comment]
Hi @themsaid 
this is my first time, contributing to laravel package.

What i did:
1. Install new Laravel
2. Add inside composer.json: the "path Repository method" and require wink "*@dev"

when i run composer update:
  The `url` supplied for the path (./../wink) repository does not exist

**Comment by Jhnbrn90** [comment]
Hi @hilmanski 
In principal you should never have to edit files in the `vendor` directory. Do note that changes made in files within this directory are likely discarded when you run `composer install` or `composer update`. 

My approach to contributing to a package is as follows.
1. Make sure to fork the GitHub repository first
1. Clone the repository to your local machine. I have a special "packages" folder
1. Install a fresh Laravel project in a "websites" folder
1. In your Laravel's `composer.json` file, add the package using the path repository method you mentioned. I have written a detailed section about this method: [Importing the package locally](https://laravelpackage.com/02-development-environment.html#importing-the-package-locally)
1. Make sure to use a different "name" in your `composer.json` file, as composer first checks packagist and if there are no records, it will try to find the package locally. 
1. Require the package in your Laravel application using `composer require {the name your used in your composer file}`.

Now, when you require the package within your Laravel application it will use a symlink to that package in your "packages" folder and any changes you make to the package are directly reflected within the Laravel application.

**Comment by hilmanski** [comment]
Thanks John for the very detail guide.
It can become one of your blog post :) so other people can find it easier in the future

cheers
