### ISSUE TITLE
Post always reverts to Published

### ISSUE THREAD

**Issue by harrysbaraini** [writingink/wink#100]
I just created a new Laravel project and installed Wink, but I'm getting the following behavior when editing posts:

- I create a post but I don't publish it
- I set the post as a draft again
- After reloading, the post reverts its status to published again.

![ezgif-5-bedd93d1f844](https://user-images.githubusercontent.com/5825285/50579552-26df5b00-0e2d-11e9-8412-1a2c48994623.gif)

**Comment by themsaid** [comment]
I can't seem to replicate this, anyone else having the same issue? 

You might need to debug the requests sent and if the database records are updated correctly in your app.
