### ISSUE TITLE
Configure Google recaptcha

### ISSUE THREAD

**Issue by barbosa89** [writingink/wink#103]
How I can configure Google recaptcha in Wink's forms? 

Thanks...

**Comment by themsaid** [comment]
Can you elaborate?

**Comment by barbosa89** [comment]
The idea is to put in the forms of login and reset password, the validation of Google recaptcha... Package: https://github.com/albertcht/invisible-recaptcha... 

Instructions from package: 

Usage
Before you render the captcha, please keep those notices in mind:

render() function needs to be called within a form element.
You have to ensure the type attribute of your submit button has to be submit.
There can only be one submit button in your form.
Display reCAPTCHA in Your View
{!! app('captcha')->render(); !!}

// or you can use this in blade
@captcha
With custom language support:

{!! app('captcha')->render('en'); !!}

// or you can use this in blade
@captcha('en')

**Comment by barbosa89** [comment]
Or how publish Wink blade views to project Views to customize
