### ISSUE TITLE
Work on 'Built-in comments system'

### ISSUE THREAD

**Issue by akiyamaSM** [writingink/wink#115]
Hello @themsaid,
I'd love to work on the comments system. do you have some restrictions?

**Comment by themsaid** [comment]
How do you plan to fight spam comments?

**Comment by noxify** [comment]
Maybe something like this: https://interworks.com.mk/laravel-spam-detection-step-by-step-guide/

Or using an external service: https://github.com/nickurt/laravel-akismet

**Comment by SimonJ** [comment]
@themsaid You mean `Disqus` :)?

**Comment by themsaid** [comment]
Yes 😅

**Comment by SimonJ** [comment]
The only I think can think of is that a self-hosted comment system is good so the user doesn't have to create an account to post comments.

Not sure if you can disable that with `Disqus`

**Comment by vootrunner** [comment]
Thank you @themsaid. Sometimes saying no is hard, but important. Part of the beauty of Wink is it's streamlined, low friction implementation. Adding a commenting system would be a cost that all of us would pay (in additional code complexity and everything associated with that), but relatively few would likely use.

**Comment by themsaid** [comment]
@vootrunner if we ever add a commenting system, it's going to be as an addon so only people who need it may have it installed. But so far, I don't think I want to go into the complexity and vulnerability of a commenting system.

**Comment by akiyamaSM** [comment]
Closed.
