### ISSUE TITLE
Allow For Code Snippet Embeds

### ISSUE THREAD

**Issue by danpastori** [writingink/wink#116]
It'd be awesome to be able to select a language for highlighting code embeds in a Wink blog. This would make it extremely easy to read for people learning new technologies.

I was thinking we could make a simple dropdown in the HTML embed that allows the user to select which coding language their snippet is in. Similar to how Notion allows you to select the language.

<img width="830" alt="screen shot 2019-01-11 at 10 40 46 am" src="https://user-images.githubusercontent.com/2365103/51053060-6c1e2e00-158d-11e9-9e63-f54e4f082dcc.png">

An awesome library for highlighting coding snippets is: https://highlightjs.org/. We can implement this into a Vue component for the package. If this is something you are interested in, I can get started and submit a PR for your review! Let me know your thoughts

**Comment by bambamboole** [comment]
I just installed wink the first time and it is pretty awesome. Congrats @themsaid !
This code embed would be apretty nice experience, but i would prefer to use [highlight.php](https://github.com/scrivo/highlight.php). This way we could process the markup in the backend and only need the css in the frontend.

**Comment by danpastori** [comment]
Oh great call! I forgot about highlight.php, great call! I agree with using that as well as it will speed everything up dramatically!

**Comment by themsaid** [comment]
Code syntax highlight is already supported using https://highlightjs.org/, select code blocks from the formatting menu.
