### ISSUE TITLE
Allow image cropping

### ISSUE THREAD

**Issue by CraftLogan** [writingink/wink#119]
Hello,
I would like to get your thoughts on using [vue-croppie](https://github.com/jofftiquez/vue-croppie) to crop the images. I went ahead and built a prototype that you can see below of how it might work.

![5d9ab484fb890960b3b0ff42b726b058 _croppietest](https://user-images.githubusercontent.com/10950466/51060524-039b7500-15be-11e9-8d66-c139a1e9dee9.gif)

If you would like I could submit a pr for this tomorrow. Thanks Logan

**Comment by themsaid** [comment]
That's awesome man, thanks :D

Looking forward to check your PR

**Comment by CraftLogan** [comment]
Awesome! I will be submitting a pr soon, but I have run into a problem with getting cropper's aspect ratio to work like needed. That is why it is taking a little longer than expected. However, I should have it fixed soon. Thanks again

**Comment by connecteev** [comment]
@CraftLogan this looks amazing. Is this going to be related to or bundled with the image layouts @themsaid  had mentioned, where you are able to left/ right / center align an image?

**Comment by CraftLogan** [comment]
@connecteev I did not add any alignment styles, but I think that could be easily added. If that is something, @themsaid would like to add then maybe I could make a pull request for that. Thanks, Logan

**Comment by themsaid** [comment]
I don't think alignment is easy to do with the current flex layout, maybe you guys know a better way :)

I'm going to close this issue then since a PR is already submitted.

**Comment by connecteev** [comment]
@CraftLogan thanks

@themsaid It's quite easy with flexbox:
See Step 6 here: https://flexboxfroggy.com/
align-items: center;
justify-content: center;

If using tailwind, use 
https://tailwindcss.com/docs/flexbox-align-items
https://tailwindcss.com/docs/flexbox-justify-content

**Comment by themsaid** [comment]
feel free to open a PR showing how we can add alignment to the flexbox layout of the editor.
