### ISSUE TITLE
Issue with searching Unsplash when deleting default text

### ISSUE THREAD

**Issue by jasonmccallister** [writingink/wink#123]
Hi @themsaid, first of all excellent work on Wink! Super elegant and it was really easy to replace the custom work I did for my site!

I did notice an issue when using Unsplash for the featured image, it defaults to the word "sunny" but as soon as I delete the word, the modal disappears. I can however select the text and start typing. I did not see a console error nor have I dived into the source code.

**Comment by themsaid** [comment]
Thanks for reporting, fixed that. Will be available next patch :)
