### ISSUE TITLE
Implement method to change the redirect path

### ISSUE THREAD

**Issue by Tjoosten** [writingink/wink#124]
For now the redirectPath. Is hard-coded. I'm wondering if we can provide a method to change this path.

**Comment by themsaid** [comment]
Which redirect path? You mean after logging in? What would you change that to?

**Comment by Tjoosten** [comment]
I was aiming at this line. 

https://github.com/writingink/wink/blob/master/src/Http/Controllers/LoginController.php#L46 

It's hardcoded but in my config. I do not use wink als URI but admin.

**Comment by themsaid** [comment]
Ah right, fixed here: https://github.com/writingink/wink/commit/71ed4ebe2728bc567d658c2eeaceb1a79a6bcc09
