### ISSUE TITLE
[IDEA] Update UI to expose post and page "settings"

### ISSUE THREAD

**Issue by jasonmccallister** [writingink/wink#128]
First of all, I love how the UI focuses on writing and I think that is right on point! One thing I have noticed is how "detached" the settings feel from the page content.

Maybe it would be nice UI touch to move the settings to icons on the right (or left) side of the page content where they have some transparency? Those icons could open the modals and continue as normal.

_(don't judge the UI or icons, I threw this together quickly)_

![ui-mockup](https://user-images.githubusercontent.com/5354908/51191111-b9faa500-18b1-11e9-9eb5-33481a2454d4.jpg)

**Comment by themsaid** [comment]
hmmm I don't feel it detached, it's just beside the "Call To Action" button, so it's pretty much in place IMO :)

**Comment by ricus-zero2one** [comment]
I really like this, it reduces the amount of clicks needed for these actions to just one, and the implementation is very clean. The icons also feel more intuitive to me than a text menu

**Comment by themsaid** [comment]
Imagine adding more items, imagine allowing package developers to add more controls to the post screen? This will make the page impossible to browse with many icons.

I honestly prefer hiding things as long as you don't need them; just write, if you want more controls click on the settings icon.

**Comment by jasonmccallister** [comment]
Feel free the close this out, for the record... I think you did a great job! I also found myself clicking twice to get to the meta data. 

Maybe line the icons up with the content versus the title?

**Comment by jasonmccallister** [comment]
![ui-mockup-2](https://user-images.githubusercontent.com/5354908/51205580-30100380-18d4-11e9-8e35-0957537420ad.jpg)

**Comment by jasonmccallister** [comment]
@themsaid I could see your point there, it could get out of control. I would look at this like my menu bar on my mac... I could have a ton of items in the bar if I want but there are ways to disable it with configuration.

**Comment by idragon81** [comment]
We could have a property in config which defines the actions to be shown here and we could hide the rest in a menu.

**Comment by themsaid** [comment]
I think I'm not going to go for this for now :) Sorry!
