### ISSUE TITLE
Featured image does not save when clicking "Save Image", only after making change to body

### ISSUE THREAD

**Issue by peanut24** [writingink/wink#129]
Hi @themsaid and friends

I noticed yesterday that when you edit a post and select a featured image, let's say you search Unsplash, but this seems to happen for both uploading and searching Unsplash, there is no request being fired off to the server for saving the image when clicking "Save Image". You can confirm this by just looking at the xhr requests in the console. 

No request gets sent to save the post when clicking "Save Image", only after you make a change to the body does the auto save kick in and sends the featured image you selected to the server.

This can be reproduced by selecting a featured image, clicking save image which will close the modal, and the refreshing the page, the image you selected will not be there anymore, however if you make a change to the body after selecting an image, and then refresh, the image will be saved.

I'm running v0.0.11.

Thanks for wink @themsaid , I've been wanting to get a simple solution for writing some small blog posts and so far wink is a great solution :)

**Comment by cpavalet** [comment]
I can confirm this. I too am experiencing the same issue. No xhr request is being sent when clicking "save image." The image gets saved in storage when selecting an image, but the storage path isn't saved in the database until you make a change to the body content.

I am also running v.0.0.11.

Thanks for this great package @themsaid ! I am just starting to play with the package myself!

**Comment by themsaid** [comment]
Fixed in: https://github.com/writingink/wink/commit/fc18b760bebe7bfaa0bb959df069eb5cfac51434

Now post will save if you change the featured image.
