### ISSUE TITLE
Login event on Wink login conflicts with existing application

### ISSUE THREAD

**Issue by snapey** [writingink/wink#139]
I'm already hooking into the `Illuminate\Auth\Events\Login` event of the Standard Auth.

When `Illuminate\Auth\Events\Login` occurs as a result of logging into Wink, an error is thrown because the authenticated user does not have the attributes I expect as it is the wink authenticated user and not my own.

The event should be renamed WinkLogin or similar so that it can be differentiated.

**Comment by intellow** [comment]
I had the same problem and I added a conditional in my handle method of the listener:

```
if(request()->getPathInfo() !== '/wink/login') {
    // do my stuff here
}
```
