### ISSUE TITLE
[note] Going to use this for my podcast site in a few weeks. 

### ISSUE THREAD

**Issue by sunscreem** [writingink/wink#14]
I've create a podcast and at the moment I'm being super lazy and manually adding each new episode. I'll be keen to give this a go and offer up feedback with anything where I had an issue. Each podcast is just an iframe with some show notes :)

**Comment by themsaid** [comment]
Do let us know how it goes :)

**Comment by sunscreem** [comment]
He @themsaid as discussed:

https://brewdognewspodcast.com/

Its a bit "forcing wink to do stuff its probably not supposed to" lol.

Only major hassle was being unable to change the dates on "older" posts to last year. Had to do that manually in the database.
