### ISSUE TITLE
Ignore migration feature

### ISSUE THREAD

**Issue by rennokki** [writingink/wink#141]
Found this at Telescope too, got fixed in the meanwhile. There's another need for ignore migration. 😆

**Comment by themsaid** [comment]
Please elaborate.

**Comment by rennokki** [comment]
Well, each time i run `php artisan migrate`, wink already run migrations for me in the default database driver. I want them to be customized, for example. It was the idea of something like `Wink::ignoreMigrations()` to be put in `register()` method in `AppServiceProvider`

**Comment by themsaid** [comment]
Upgrade to the latest release, we don't publish the migrations there. You'll need to run wink:migrate to run wink migrations, otherwise it would migrate your project migrations.
