### ISSUE TITLE
Multiple blogs with one wink installation

### ISSUE THREAD

**Issue by swapnilsarwe** [writingink/wink#142]
This is a very specific requirement, just need to get a suggestion from others regarding this.

We are a family of 4 each maintaining their own personal blog with single laravel installation, is there a way I can use the wink to manage multiple blogs with one custom field (maybe 'domain') which I can filter while fetching from DB.

Otherwise I can create another packages just as an extension of the current manage to add this custom requirement, or else may be adding hooks #120 can give that ability.

**Comment by themsaid** [comment]
Hey,

Depending on the domain name, you can configure the database connection Wink should be using, you can do that in a Service Provider.

**Comment by swapnilsarwe** [comment]
Will give it a try and reopen the issue if any help needed. Closing for now.
Thanks @themsaid
