### ISSUE TITLE
[Idea] Admin Bar feature

### ISSUE THREAD

**Issue by shrft** [writingink/wink#144]
Hi. I think it would be better if wink has an easy way to add admin bar to it's front page.
I have created a [package](https://github.com/shrft/laravel-admin-bar) to achieve this for laravel and I am willing to write wrapper package for wink.
I just want to know if this feature is needed for wink first.
thanks.

**Comment by themsaid** [comment]
Hey,

I don't think I'm going to use it honestly :) I'll just prefer going to the backend and do thing there.

Thanks for the initiative :)

**Comment by shrft** [comment]
@themsaid hi. ok. thank you for your reply.
