### ISSUE TITLE
Trigger Laravel Events on main actions

### ISSUE THREAD

**Issue by rennokki** [writingink/wink#146]
That would be awesome to actually be able to extend some custom logics in case the post is updated or so through events and listeners. :D

**Comment by themsaid** [comment]
Eloquent model events are already triggered, you can listen to these and apply the changes you need.

**Comment by rennokki** [comment]
Yea, at first I didn't think about that. An observer would do the job 💃

**Comment by DominikGeimer** [comment]
Can someone give me an example? 

I have a model Article wich extends WinkPost and I want to observe the store method and when the event happens I want to Artisan::call('scout:reimport'). 

But I does not work. Anything I have overlooked?
