### ISSUE TITLE
attribute type="ecmascript-6" in vue component script tags - is it correct?

### ISSUE THREAD

**Issue by mikew1** [writingink/wink#149]
I hit this because sublime vuejs syntax highlighter breaks in the presence of this exact attribute tag. 
It does not break if the attrib. is either `type="text/javascript"` or `type="text/ecmascript"`.
But with `type="text/ecmascript-6"`, all syntax highlighting within the script tag is broken.

YES, this may not be an issue with wink source.  But I'm asking to get clarification whether that is really the case.  I have looked online for details on this but since it's about webpack and the millions of versions of the language we refer to as "javascript", I fear I would get totally lost.

Hence, can the author please kindly confirm if in their opinion `type="text/ecmascript"` would be just as good?   Thanks much.  If the answer is no, then I'll report an issue to the vuejs plugin dev.

**Comment by themsaid** [comment]
Hey,

I think we can change it to `type="text/ecmascript"`. I use PHPStorm and it used to complaint if this is not present but I think it's ok now in their latest versions.

**Comment by mikew1** [comment]
Hi, I've made a pull request. Please feel free to correct me if I do something wrong. Thanks, Mike
