### ISSUE TITLE
Sintax high light doesn't work

### ISSUE THREAD

**Issue by barbosa89** [writingink/wink#150]
Code formatter doesn't work fine, The code is in a single line but in editor is ok, only printing post content with Blade. I am using: https://highlightjs.org/usage/

`<?phpuseApp\Post; $posts = Post::all();`

https://omarbarbosa.com/posts/optimization-of-eloquent-queries-to-reduce-memory-usage

![code](https://user-images.githubusercontent.com/9729573/52389517-ca8ddd80-2a61-11e9-808f-8919d7646455.png)

**Comment by themsaid** [comment]
hmmm I can't seem to replicate it, works fine for me. You'll need to dig into that a little bit.

**Comment by barbosa89** [comment]
Hi @themsaid, I am trying to print an article in my post page. I am querying the article:

```
$post = WinkPost::where('slug', Input::clean($slug))
    ->with(['tags', 'author'])
    ->first();

return view('templates.post', compact('post'));
```

In **post.blade.php**, I am printing the text:

```
<div class="row">
    <div class="col-12">
        <article>
            {!! $post->body !!}
        </article>
    </div>
</div>
```
To enable sintax high light, I have installed the library **highlight.js**:
`
npm install highlight.js --save-dev`

After, in my webpack I am trying this:

```
.scripts([
  'node_modules/highlight.js/lib/highlight.js'
], 'public/js/highlight.js')
```

Finally, in **post.blade.php**:

```
<script src="{{ asset('js/highlight.js') }}"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

But the code is printed wrong:

![e](https://user-images.githubusercontent.com/9729573/59534208-3d491280-8eb3-11e9-9d61-9db90ac9f1ca.png)

The code examples when writing the article, does not have line breaks, is shown in the same line. I would really appreciate your guidance on that.

**Comment by devcircus** [comment]
highlightjs is already included. 
https://github.com/writingink/wink/blob/master/resources/views/layout.blade.php#L17

Create your code block using the code-block button of the WYSIWYG so that the markup is saved correctly, then highlightjs, which is available globally, will take care of the rest. Make sure you’re also including one of the highlightjs css stylesheets.

**Comment by barbosa89** [comment]
Thanks @devcircus, do you mean to write an article? Because I do not have errors in Wink panel, all is ok, my problem is when I trying print an article with my own blade file...

**Comment by barbosa89** [comment]
I found the error, this was a middleware from the laravel-page-speed package:

`\RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class`

The package erased all blank spaces
