### ISSUE TITLE
"The ability to crop uploaded images" feature in 0.0.12 release

### ISSUE THREAD

**Issue by m4tlch** [writingink/wink#153]
Has this feature "Added the ability to crop uploaded images." been actually added to the last release 0.0.12? I cannot see it nowhere at wink's admin pages. https://qsnapnet.com/snaps/jp01clxzptl

**Comment by themsaid** [comment]
Make sure you re-publish the compiled Wink assets.

**Comment by m4tlch** [comment]
Ok, I made re-publish and found this feature https://i.imgur.com/zpa7rTr.png . Thanks
