### ISSUE TITLE
Anyone seen this?

### ISSUE THREAD

**Issue by connecteev** [writingink/wink#157]
Just stumbled across this
https://cnvs.io/
https://github.com/cnvs/canvas

@themsaid assume this was done with your permission and is legal? As an aside, the core contributor is quite active (probably why his repo is getting traction).

**Comment by noxify** [comment]
It seems so: https://github.com/cnvs/canvas/issues/427

**Comment by themsaid** [comment]
I consider it a Fork from wink 🤷‍♂️I was frustrated at first but then don't care anymore.

**Comment by connecteev** [comment]
I would've expected some form of attribution, at the very least. Regardless, it's good for the community  I guess, and I'm excited to see both codebases evolve.
