### ISSUE TITLE
Can't change avatar?

### ISSUE THREAD

**Issue by shone83** [writingink/wink#160]
It seems that I can't change avatar in user profiles. Is there any format or size limitations for avatars? Image upload in post works fine.

**Comment by themsaid** [comment]
I can't seem to be able to replicate this, seems like an issue with uploads in your app.

**Comment by shone83** [comment]
I just follow instruction for installation and everything install fine and everything works fine include pictures inside posts. But, ehn i tried to upload pic in Profile->Upload an avatar->select pic->open->save simply nothing happens. How can give you more info?

**Comment by alejandrozepeda** [comment]
Same issue here, in a fresh installation.

**Comment by CraftLogan** [comment]
@shone83 @alejandrozepeda  are you seeing any errors in your chrome dev console?

**Comment by CraftLogan** [comment]
Also what image type are you uploading png jpg?

**Comment by srdjanmarjanovic** [comment]
Same issue here. I might try to resolve/debug this

**Comment by srdjanmarjanovic** [comment]
No errors in console, no requests sent. Nothing. Just get the file picker and when I select the image, the file picker is closed and nothing happens. No matter what type or size of image i select, i get the same result.

**Comment by srdjanmarjanovic** [comment]
Ok, so I followed the [Contributing docs](https://github.com/srdjanmarjanovic/wink/blob/master/CONTRIBUTING.md) and finally managed to get an error: 

`Vue warn]: Unknown custom element: <croppie-modal> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Edit> at resources/js/screens/team/edit.vue
       <Root>`

**Comment by srdjanmarjanovic** [comment]
Fixed it in #163

**Comment by shone83** [comment]
I have no errors in chrome dev console and I try png and jpg but nothing works. 
I try to change what @srdjanmarjanovic says in ``` resources/js/screens/team/edit.vu``` but sam result.

**Comment by srdjanmarjanovic** [comment]
It probably serves you the old compiled Vue component. You can try to checkout my package instead of the official package and try with it

**Comment by srdjanmarjanovic** [comment]
1. `git clone git@github.com:srdjanmarjanovic/wink.git` to some directory on your local machine
2. Delete `writingink` diretory from the `vendor` directory of your local Laravel installation
3. Add the following code to your `composer.json` and adjust `url` to match your cloned package path: 
```
"repositories": [
    {
        "type": "path",
        "url": "/path/to/cloned/wink/directory"
    }
]
```
4. In `composer.json` change the line similar to `"writingink/wink": "^0.0.12"  into `"writingink/wink": "*@dev"`
5. run `composer update` 
6. go into the `/path/to/cloned/wink/directory` and run `yarn install`. If you don't have `yarn`, install it.
7. run `yarn run dev`
8. in your Laravel directory, run `php artisan serve` 

That should be it. Bear in mind that you should revert to the original package if and when my changes get merged.
