### ISSUE TITLE
Getting modal with validation error: The author id field is required

### ISSUE THREAD

**Issue by tekord** [writingink/wink#161]
I just installed wink from scratch in my project, which had no database and no user support. After successful installation and login to admin I tried to create a new post, but once I wrote some paragraphs I got modal with validation error: The author id field is required. It happened after request to wink/api/posts/new. I close the modal and it appeared again. So, I can't do anything.

**Comment by tekord** [comment]
Found the bug I guess. Action \Wink\Http\Controllers\PostsController::show does NOT include author ID to response. But this response is used by Vue component to fill the editor's form data (js/screens/posts/edit.vue::mounted). So, author_id is absent there.

**Comment by themsaid** [comment]
I can't replicate this, works fine for me.

**Comment by tekord** [comment]
1. I open in browser /wink/posts/new (I logged in before).
2. Wink's JS does 3 XHR:

tags | GET | 200 | http | xhr | app.js:285
team | GET | 200 | http | xhr | app.js:285
new | GET | 200 | http | xhr | app.js:285

tags response is empty array `[]`; team response is:

```
[{"id":"740aca71-c0f0-4571-9408-6b6417123ce1","slug":"regina-phalange","name":"Regina Phalange","email":"admin@mail.com","bio":"This is me.","avatar":"https:\/\/secure.gravatar.com\/avatar\/edb0e96701c209ab4b50211c856c50c4?s=80","created_at":"2019-02-19 20:58:46","updated_at":"2019-02-19 20:58:46","meta":null,"posts_count":0}]
```
(this user was generated automatically after wink installation)

new response is:

```
{"entry":{"id":"861d802c-f9ce-4bf0-9b94-02896b7b8364","publish_date":"2019-02-23 12:22:00"}}
```

3. Now I type something in editor, Wink's JS does the following XHR request:

new | POST | 422 | http | xhr | app.js:285

The response is: {"message":"The given data was invalid.","errors":{"author_id":["The author id field is required."]}}

4. I installed Wink into separated folder as described in CONTRIBUTING.md file. I added Vue.config.debugTools = true and build it. Now I can see data of editor form:

```
$route
authors:undefined
currentTab:"post"
entry:Object
id:"861d802c-f9ce-4bf0-9b94-02896b7b8364"
publish_date:"2019-02-23 12:22:00"
errors:Object
author_id:Array[1]
0:"The author id field is required."
form:Object
author_id:""    <- !!! IS EMPTY, BUT I LOGGED IN
body:"<p>впвзшщывп</p>"
excerpt:""
featured_image:""
featured_image_caption:""
id:"861d802c-f9ce-4bf0-9b94-02896b7b8364"
meta:Object
publish_date:"2019-02-23 12:22:00"
published:false
slug:"draft-861d802c-f9ce-4bf0-9b94-02896b7b8364"
tags:Array[0]
title:"Draft"
id:"new"
postBodyWatcher:ƒ unwatchFn()
publishingModalShown:false
ready:true
saveKeyboardShortcut:ƒ (event)
seoModalShown:false
settingsModalShown:true
status:""
tags:undefined
```

5. Now let's look at `fillForm` function in resources/js/screens/posts/edit.vue (line 136):
```
fillForm(data) {
  ...
  if (this.id != 'new') {
    ...
    this.form.author_id = data.author_id || '';
```

`author_id` is populated only if the current post is not new. My post is obviously new.

6. `fillForm` function is called inside `mount` function. `data` argument is the response of XHR request (/wink/api/posts/new). As I describe it in section 2, the response does not contain author_id field:

```
{"entry":{"id":"861d802c-f9ce-4bf0-9b94-02896b7b8364","publish_date":"2019-02-23 12:22:00"}}
```

**Comment by tekord** [comment]
Suddenly I tried wink again, updated from the repo and it works.

**Comment by tekord** [comment]
Any news here?

**Comment by askaoru** [comment]
Had this issue on fresh install as well. On the /api/post/new POST call the `author_id` on the request parameter was `""`.

Weirdly enough, after trying to debug it and restarting my php-fpm the issue seems to go away on it's own.

**Comment by ChrisSFR** [comment]
I had Resource::withoutWrapping(); set in my AppServiceProvider.
That influenced the Wink Resources also.
https://github.com/writingink/wink/issues/132#issuecomment-456400747

There's a pull request #190  from mabasic which fixes this issue.
