### ISSUE TITLE
[improvement] Image url

### ISSUE THREAD

**Issue by ana-lisboa** [writingink/wink#162]
Image paths ideally shouldn't be stored with the domain url.

Imagine (as it's happening to me), i am developing a site on localhost. I then move that site to it's domain.
I then have to save all the images again because on the db, the images are stored like this:
//localhost:3000/storage/image_path

**Comment by devcircus** [comment]
Use the provided path configuration options for your different environments.

**Comment by stefanbauer** [comment]
@themsaid issue can be closed (just to have clean issues) :)
