### ISSUE TITLE
Unique Rule SQL Injection Warning

### ISSUE THREAD

**Issue by nguyentranchung** [writingink/wink#164]
https://github.com/writingink/wink/blob/f19afd6157b09b5835d1e4f52d54260ad27549d7/src/Http/Controllers/PostsController.php#L84

unique rule is in hadPostsController, PagesController, TagsController, TeamController file.

**Comment by nguyentranchung** [comment]
[https://blog.laravel.com/unique-rule-sql-injection-warning](https://blog.laravel.com/unique-rule-sql-injection-warning?ref=chungnguyen.xyz)

**Comment by devcircus** [comment]
I thought @themsaid fixed this on the Laravel side, so this would no longer be an issue, but I may be mistaken.
