### ISSUE TITLE
is it possible / difficult to decouple the vue front-end and have it be standalone ?

### ISSUE THREAD

**Issue by vesper8** [writingink/wink#167]
I'm looking to intergrate a blog in my vue-cli front-end site which interacts with a Laravel installation strictly through API, consider them to be on separate servers.

Is Wink suited for this? It may not work out of the box but would it be very hard to use the Vue components and stick them on a standalone site and then fetch the posts content through a Rest API? Including for editing/adding posts.. or is this completely out of scope for this project?

So many good CMSs based on Laravel that make use of Vue but it seems none of them are decoupled

**Comment by themsaid** [comment]
Vue is used in the backend. In your frontend you can use whatever you want.
