### ISSUE TITLE
resource wink was not found

### ISSUE THREAD

**Issue by supportskins** [writingink/wink#168]
I installed the Wink package as per the instructions however it does not load. I am able to see the login page and after I login I am displayed the following message:

> Not Found
> The requested resource /wink was not found on this server.

I tried to install Wink on an existing Laravel application as well on a fresh Laravel installation. In both cases I faced this error. Please note, I am trying to install Wink on my localhost before I can push it into production.

How can I resolve this issue?

**Comment by ghobaty** [comment]
Hey there, it might be because your `WINK_PATH` environment variable starts with a forward slash.

**Comment by antoni568** [comment]
Hello friends, I have the same problem, I verify the forward slash but not not is the problem. Could you help me with it please.

**Comment by wpearse** [comment]
What is the output of this command:

`php artisan route:list | grep wink`

**Comment by tchmonkey** [comment]
I'm having the same issue.  Here is my output from the command @wpearse suggested.
![wink-output](https://user-images.githubusercontent.com/5742785/76327900-f876ce80-62c0-11ea-9b5b-ea0f550fd61c.jpg)
