### ISSUE TITLE
Question - Please explain how wink's front end authentication is working?

### ISSUE THREAD

**Issue by mikew1** [writingink/wink#172]
I'm a little bit confused about how wink's vue front end to its admin panel is doing api authentication - it doesn't seem to be using passport (hence JWT), though I realise now my understanding of these concepts may be a little shaky.

I was under the impression that any kind of xhr request must use JWT to be able to authenticate itself, at least that being how to do it with laravel. But I think I have some concepts a bit jumbled here. 

Would anyone be kind enough to explain exactly how wink's vuejs front end is authenticating its requests?

I've been reading wink's ServiceProvider and looking into the guard it registers. I know that wink has its own users table of course, and the 'wink' guard uses session driver (not token), this being how it logs in. The other part of the guard is of course to say where users are stored, which points to the wink_users table.

The bit that confuses me (due to my misunderstanding no doubt) is how the api can be authenticating when there is no 'token' driver in sight.

I developed another app (my first major laravel app) and for that I installed Passport (on v. 5.5) via which the js front end to it does token auth when doing its xhr requests.

However, I'm now wondering whether I got that a bit wrong in the sense that it simply wasn't necessary.  Is passport needed only where you truly want stateless (token) auth for external "third party" api clients that you know you will have which you also know will never want to log in in the normal way ever, and the JWT thing is just a way to let your own front end use that same system?

Could I have just not used passport at all, and used a web guard even on api routes?  Since that's using the 'session' driver, which works via a cookie, that means an xhr request must be able to send the cookie so laravel knows it's logged in.

I guess that's the point. I found [this link](https://stackoverflow.com/questions/2870371/why-is-jquerys-ajax-method-not-sending-my-session-cookie) which seems to discuss this technical point.

It says:
> "AJAX calls only send Cookies if the url you're calling is on the same domain as your calling script".

Would anyone care to explain exactly how wink is authenticating its api to clear up my misunderstanding a bit?   I'd like to contribute to wink source in a few ways as I plan to roll it out for a significant app that a few people are going to be using.

Thanks!

**Comment by mikew1** [comment]
Sorry - resolved.  If it's of any interest when I built my first api with laravel I ended up using Passport unnecessarily and had been confused about what a simple api needed to be ever since then.   

All I needed was some json endpoints for my web front end, but somehow, perhaps in an urge to learn, was sold on the idea of "a real, stateless, token api you could also use for your web front end".   Of course, all I needed was a regular web route that just happened to return json instead of html.   Oh dear.. what a diversion.  Well, you live and learn...  :)

**Comment by connecteev** [comment]
@mikew1 your last comment was interesting, as I've been confused about passport myself. I want to have a front-end in Nuxt/vue that is it's own layer, which sends Ajax/axios requests to a Laravel App (API). 

Do I need to authenticate / project my ajax requests? If so, how? And is Laravel passport overkill? I assume from your comment, thatyou were / are in a similar boat. Thanks :)

**Comment by mikew1** [comment]
I'm no SPA expert I'm afraid so I couldn't possibly be authoritative on that, apologies.
Passport does full OAuth, which is a gigantic thing, like how you let other apps access your github and only in specific authorised ways. It's very granular. There are simpler approaches even for stateless token auth in laravel, I believe. I saw some packages for that.  But, my hunch is, if, whatever your front end is, (& it doesn't matter what it is) if that front end does a login with laravel and therefore **sets laravel login cookie in your browser** (use dev tools to check if it's there), then you should be able to just set middleware web & auth on your laravel routes and then laravel will check for login cookie to auth.  I don't believe it matters if it is a web request or axios, cookies I think work the same. 

What is totally different is if you want to authenticate something that does not login in the broweser at all. That in my mind is a "real" api and the usual method is a bearer token in every request, in the http header.  (Passport, and OAuth, indeed handle that, and much else besides). Hope that helps.
