### ISSUE TITLE
Error..

### ISSUE THREAD

**Issue by technodesign-dn** [writingink/wink#173]
When installing wink (in the step php artisan wink:migrate) I get an error.
My database in laravel "wink"
![InkedD5-1xwNWkAAEaBv_LI](https://user-images.githubusercontent.com/45261338/57325582-04c75380-7113-11e9-8c6f-8aeffacc84ca.jpg)
![D5-2PfIWAAU8g6s](https://user-images.githubusercontent.com/45261338/57325586-085ada80-7113-11e9-9e88-56f0f92eb51d.png)

**Comment by technodesign-dn** [comment]
in config/wink.php 

 'database_connection' => env('WINK_DB_CONNECTION', 'wink'),

**Comment by NexPB** [comment]
In your .env file you should set (if mysql is the database you'll be using)
```
WINK_DB_CONNECTION=myql
```
