### ISSUE TITLE
BlogController error

### ISSUE THREAD

**Issue by prodigital-design** [writingink/wink#174]
when specifying 

Route::get('/', 'BlogController@index');
Route::get('/{tag}/{slug}', 'BlogController@post'); error appears

![image](https://user-images.githubusercontent.com/45261338/57360641-4e4f8700-7183-11e9-92f4-1bf09a295185.png)

**Comment by technodesign-dn** [comment]
Is there a "wink" with a customized blog?

**Comment by technodesign-dn** [comment]
> You've got to create a controller yourself https://laravel.com/docs/5.8/controllers.

Is there a "wink" with a customized blog?

**Comment by lucasdcrk** [comment]
Duplicate of #175
