### ISSUE TITLE
Add ability to change link target

### ISSUE THREAD

**Issue by stefanbauer** [writingink/wink#183]
At that moment, it's not possible to create internal links. All links have a `target=_blank` per default. In most cases this makes sense, but sometimes if you link internally from one post to another, for instance, this does not make sense.

Therefore it would be nice if such a functionality would be there.

**Comment by themsaid** [comment]
Removed target="_blank" from links in v1.0

releasing soon

**Comment by iAmKevinMcKee** [comment]
Do you plan to add the ability to configure whether or not a link opens in a new tab or not? Seems like right now I can only add links that open in the same window/tab.
