### ISSUE TITLE
Advanced Custom Fields using Wink

### ISSUE THREAD

**Issue by Dinesh-Iksula** [writingink/wink#186]
How can one achieve the functionality similar to [Advanced Custom Field](https://wordpress.org/plugins/advanced-custom-fields/) for WordPress?

It will be very useful if we can create fields like:

> 1. Text field
> 2. Textarea (with and without the editor)
> 3. Radio buttons/checkboxes
> 4. Single/Multi-select dropdown
> 5. Image upload
> 6. File upload
> 7. Looping the above-mentioned fields

**Comment by themsaid** [comment]
I don't want to make this package to do more than what a blogging/publishing platform does :)
