### ISSUE TITLE
Posts/Page Export

### ISSUE THREAD

**Issue by WyattCast44** [writingink/wink#188]
Migrating some wink created content to a new site/instance of wink and was thinking it would be cool to have a way to export the created posts/pages built into the UI of the package.

@themsaid if this is something you think would be useful, I can try and work on something?

Respectfully, 

Wyatt :)

**Comment by connecteev** [comment]
@WyattCast44 did you end up merging a PR for this?

**Comment by WyattCast44** [comment]
@connecteev no, closed it due to inactivity. I also built out a small tool for myself, link here: https://github.com/WyattCast44/winkexport/blob/master/README.md. Still very rough but worked for my use case. The accompanying importer is in works. Let me know if you wanna check it out and I’ll push it up
