### ISSUE TITLE
Re-install command 

### ISSUE THREAD

**Issue by DivineOmega** [writingink/wink#19]
Currently the install command will not update the views and config if they have changed due to a `composer update`. Would it be sensible to modify the lines to include the `--force` parameter, as follows?

```
$this->callSilent('vendor:publish', ['--tag' => 'wink-assets', '--force']);
```
```
$this->callSilent('vendor:publish', ['--tag' => 'wink-config', '--force']);
```

Alternatively, we could create a re-install command that does this. What does everyone think?

**Comment by themsaid** [comment]
I don't want to override your config file after you've changed it. To make sure the assets are updated after a change in Wink you can run:

```
php artisan vendor:publish --tag=wink-assets --force
```

**Comment by DivineOmega** [comment]
@themsaid Thanks for the reply. Do you think creating a `wink:reinstall` or `wink:upgrade` command that does this for you would be useful?
