### ISSUE TITLE
Add exclude method on posts while querying

### ISSUE THREAD

**Issue by psgganesh** [writingink/wink#192]
Adding exclude method on posts while querying

https://medium.com/@InaniT0/sometimes-when-querying-some-models-we-want-to-exclude-colmuns-from-the-results-the-same-as-using-b2001af4b0ec

**Comment by psgganesh** [comment]
@themsaid - I have fix for this, need permission to push this fix

**Comment by ventrec** [comment]
Any reason for not using a select (or setting the columns in `get`) while querying?

```php
$medicines = \App\Medicine::get(['id', 'name']);
```

This would give me the id and name fields of Medicine, without the description.

(Btw. Medium is not available in Egypt, where themsaid resides, so he can't see the linked article.)

**Comment by themsaid** [comment]
What @ventrec says.

Wink is just a backend. You can use the Post model to query posts as you wish in your frontend.
