### ISSUE TITLE
Image cropping not working after build

### ISSUE THREAD

**Issue by ahmic** [writingink/wink#193]
Followed contribution guide setup but have image crop issues after running `yarn run watch/dev/prod`. Got build successful message.

After choosing an image crop does not work. There is no any errors in the console, just this strange behaviour 

https://www.youtube.com/watch?v=jsOjOBcxnYE&feature=youtu.be

**Comment by ahmic** [comment]
Digging around and found that croppie styles are missing after compiling. As per croppie documentation css must be imported manually:

`import 'croppie/croppie.css'`

This line should be in `resources/app.js` file?

**Comment by themsaid** [comment]
fixed in 1.0

thanks :)
