### ISSUE TITLE
Posts pagination not working

### ISSUE THREAD

**Issue by ibrunotome** [writingink/wink#199]
I'm with 48 posts right now and the hasMoreEntries in the vue component is not updading to `true` to enable the load more button.

**Comment by malic0** [comment]
> I'm with 48 posts right now and the hasMoreEntries in the vue component is not updading to `true` to enable the load more button.

A Lil code will help @ibrunotome 
Show me your controller method.

**Comment by ibrunotome** [comment]
Hi @malic0 , there is no external code, I mean the own wink package content: https://github.com/writingink/wink/blob/master/resources/js/screens/posts/index.vue

**Comment by themsaid** [comment]
Fixed that in 1.0
