### ISSUE TITLE
Slug doesn't update when changed.

### ISSUE THREAD

**Issue by astr0naugh7** [writingink/wink#20]
1) When I clicked the settings button for the post, it had: 5e51cfe1-5cad-4d50-9ba1-7d12752522ca and I updated to 6-reasons-blah-blah and it keeps showing when I check the settings but it doesn't update in the URL, the URL stays 5e51cfe1-5cad-4d50-9ba1-7d12752522ca even after refreshing / updating the post.

2) How do you share posts/blog with the public? Is it just the URL to the page? Trying to go to "url.com/blog" just takes me to the login page.  (I've updated the path in config/wink.php) Do I need to straight up make a controller to handle it? I thought that would all be built in.

3) Also, even after updating the path in config/wink.php when I logout, it uses the 'wink/logout' path, should it not update with the path as well?

I really really want to use this but don't want to think it's much further along than it is. Thanks for your hard work and I really think this could replace Ghost.

**Comment by themsaid** [comment]
@astr0naugh7 the URLs in the admin panel uses the UUID not the slug, the slug is for your interface. Wink isn't shipped with client facing controller or views, you need to build these yourself.

There's an example in the readme file on how to get a list of posts for your display, you can use the same approach to server a route that you define, say `/blog/{slug}` then in your controller use that slug to query for the post and display it.
