### ISSUE TITLE
[support] - how to programmatically log in?

### ISSUE THREAD

**Issue by beck24** [writingink/wink#200]
It seems the ability to have the User class manage the blog has already been discussed, I'm wondering if it's possible to programmatically log in as a WinkAuthor?

I've created a WinkAuthor for my User, I just want to create a simple button that takes them to the blog admin and logs them in automagically.

I tried `Auth::login($winkAuthor)` but that was unsuccessful.  Any suggestions?

**Comment by beck24** [comment]
I figured it out.

In case anyone else is searching for it you need to use the Wink auth guard first

    auth('wink')->login($winkAuthor)

**Comment by skino2019** [comment]
i might need to ask you some questions on this lol. im trying to do the same thing with Laravel Fortify
