### ISSUE TITLE
404 Not found when go to app-name.com/wink

### ISSUE THREAD

**Issue by pazitron1** [writingink/wink#203]
I installed wink in my existing Laravel app. Followed all steps:

composer require writingink/wink
php artisan wink:install
php artisan wink:migrate

got the confirmation message: 
Wink is ready for use. Enjoy!
You may log in using admin@mail.com and password: xxxxxxxxxxx

Went to my-app.com/wink but it returned 404 not found. 

What could be the problem?

**Comment by omitobi** [comment]
`php artisan route:clear`?

**Comment by pazitron1** [comment]
Apologies, I did not realise I changed wink_path to manage, hence /wink goes to 404. No more coding late at night :S

**Comment by pazitron1** [comment]
human error
