### ISSUE TITLE
"ReflectionException (-1) Class does not exist"  laravel  6

### ISSUE THREAD

**Issue by michaelNgiri** [writingink/wink#207]
I get "ReflectionException (-1) Class does not exist" while trying to install wink on Laravel  6
![Screen Shot 2019-10-28 at 12 33 28 PM](https://user-images.githubusercontent.com/25643308/67675410-509add00-f97f-11e9-8817-fa00b3b06f14.png)

**Comment by WyattCast44** [comment]
Try clearing your cache

```bash
php artisan cache:clear
```

Hope this helps!

**Comment by michaelNgiri** [comment]
That's what I thought, but I have tried all the commands I know:
`php artisan config:clear`
`composer dump-autoload`
`php artisan view:clear`

No luck!
