### ISSUE TITLE
Cannot Delete a Page

### ISSUE THREAD

**Issue by vasuratanpara** [writingink/wink#209]
![Screenshot from 2019-11-01 03-18-48](https://user-images.githubusercontent.com/15255654/67988738-e3c16480-fc56-11e9-8a92-2b2a54b76aae.png)
I wasn't able to delete page after creating it. I checked it on Chrome(Version 78.0.3904.70 - 64 bit) and Firefox (Version 70.0 - 64 bit).

**Comment by robindirksen1** [comment]
Did you get a console error or something that maybe can help with troubleshooting this issue?

**Comment by tvbeek** [comment]
> 
> 
> Did you get a console error or something that maybe can help with troubleshooting this issue?

I have the same error and see this in my console:
![image](https://user-images.githubusercontent.com/2026498/68480416-05ad7f00-0235-11ea-8843-a24852ef72e1.png)

**Comment by themsaid** [comment]
Deleting seems to be working fine. Seems like there's an error coming from the server? Check your logs and open a new issue in case you have an exception we can look at.
