### ISSUE TITLE
Username / Password in Production

### ISSUE THREAD

**Issue by pt-phone-home** [writingink/wink#210]
Hi, 

I have been using wink in dev env for a couple of weeks to get up and running. It's great. 
However... I have just pushed my blog to production and I can't find my username and password as there is no console for them to output to. Any help would be much appreciated. 

For note I am using Laravel Forge for deployment. 

Thanks

Peter

**Comment by pt-phone-home** [comment]
I have a temporary work-around where I ssh'd into my database and manually added my credentials from my local env and I'm up and running again but I would still like to know a better way around this.

**Comment by zhanang19** [comment]
Hmm, I think you can run command `php artisan tinker` from your server to update your credential.

I can't guarantee it will workly run, but from the theory it can be done, just try it.

**Comment by devcircus** [comment]
I always create a console command that allows me to create an administrator via credentials defined using environment variables. Not wink specific, just in general for Laravel apps. To me, it's the most secure way to do it. 🤷🏻‍♂️

I guess tinker could work fine but I prefer
```
php artisan admin:create
```
