### ISSUE TITLE
How to configure wink/config file with existing database having password

### ISSUE THREAD

**Issue by Kalpeshpatelbyk** [writingink/wink#211]
![winkerr](https://user-images.githubusercontent.com/11476137/68528354-82b12500-0317-11ea-9609-915b1f720740.png)

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=temp
DB_USERNAME=root
DB_PASSWORD=xxxxxxxx123
WINK_DB_CONNECTION
 i had database and existing connection with password
adding 
WINK_DB_CONNECTION 
used following command
php artisan wink:migrate gave error database wink not configure

help will appreciated thank in adavance

**Comment by tvbeek** [comment]
You can use the same connection configuration for wink as for the normal DB. So:

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=temp
DB_USERNAME=root
DB_PASSWORD=xxxxxxxx123
WINK_DB_CONNECTION=mysql
```

Or what I did, change your config file wink.php from 
```php
'database_connection' => env('WINK_DB_CONNECTION', 'wink'),
```
to
```php
 'database_connection' => env('WINK_DB_CONNECTION', env('DB_CONNECTION', 'mysql')),
```
And you don't need to set the WINK_DB_CONNECTION because it will use the DB_CONNECTION if the WINK_DB_CONNECTION isn't set.

**Comment by ahmedsliman** [comment]
You can add an array element to the database.php

```
        'wink' => [
            'driver' => 'mysql',
            'url' => env('WINK_DATABASE_URL'),
            'host' => env('WINK_DB_HOST', '127.0.0.1'),
            'port' => env('WINK_DB_PORT', '3306'),
            'database' => env('WINK_DB_DATABASE', 'forge'),
            'username' => env('WINK_DB_USERNAME', 'forge'),
            'password' => env('WINK_DB_PASSWORD', ''),
            'unix_socket' => env('WINK_DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('WINK_MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
```

Then use WINK_DB_ vars in .env file
