### ISSUE TITLE
Problems with tag ordering

### ISSUE THREAD

**Issue by milan-patartics** [writingink/wink#214]
First of all I want to say it's really good to have this project. It's awesome I really like it.

But unfortunately there are some problems with the tags. I made a system where the first tag is the main category of the post and other tags are used as normal tags. This way we can display related categories under each posts to display content in the same category.

So tag ordering is important in this case, but I realized that tags are reordered on post save, and the user inputted order changes to a different order (ordered by tag creation time I guess). So when I access tags via $post->tags it returns me a reordered list and this way we can not define the main tag as a category.

Is there any way to keep the order entered by the user after saving the post?
It would be really nice to have.

Can I do something to prevent the original ordering entered by the user?

**Comment by tvbeek** [comment]
In basic it isn't ordered, see: https://github.com/writingink/wink/blob/master/src/WinkPost.php#L66 I think you need to have a custom option to set the main category.

**Comment by milan-patartics** [comment]
> In basic it isn't ordered, see: https://github.com/writingink/wink/blob/master/src/WinkPost.php#L66 I think you need to have a custom option to set the main category.

Not really, because it only become ordered when you get the tags. Should be returned ordered by relation creation time defined in the relation table. So we could have to ability to keep the ordering.

Why should the tags be displayed in the same order everywhere? Same order just causes duplicate content.

**Comment by themsaid** [comment]
I'd accept a PR that adds categories support on branch 2.x
