### ISSUE TITLE
Description of wink - adding Cms

### ISSUE THREAD

**Issue by ser-gi-o** [writingink/wink#215]
First off, great package!  this is something i've been looking for for a while.  A package that can handle my cms needs within my app.  

However, I did have a difficult time finding it.  I've been looking for cms package not a publishing platform.  

May I suggest adding Cms to the title.  For example:
"A Laravel-based publishing platform" **to** "A Laravel Cms and Publishing Package".

I think it would create more awareness for this awesome package and its structure appears to follow the Laravel Official Packages like Telescope rather than being its own standalone platform.

**Comment by themsaid** [comment]
Thanks. Will add that :)
