### ISSUE TITLE
Accessing and sharing blog posts with guests

### ISSUE THREAD

**Issue by oliverbj** [writingink/wink#218]
Hi everyone

First of all, what a great package! Very easy to use and it looks and feels great.

I have created my first blog post, that I would like to share with my network. I don't expect all of my network to create an account on my application just to read this blog post.

Is there anyway that I can publish it, so users are not redirected to `/blog/login`?

**Comment by petersowah** [comment]
@oliverbj Were you able to resolve this? If so, can you please share?

**Comment by oliverbj** [comment]
@petersowah I initially misunderstood the `/blog/login` as this is used for me (the administrator). You have to create your own pages (for example all blog posts, view specific blog post) and the theme.

I simply used the examples given in the documentation. For example, for the page "all blog posts", I just added this in the controller:

```php
use Wink\WinkPost;

public function index()
{
    $posts = WinkPost::with('tags')
        ->live()
        ->orderBy('publish_date', 'DESC')
        ->simplePaginate(12);

    return view('blog.index', [
        'posts' => $posts
    ]);
}
```

**Comment by petersowah** [comment]
Thanks @oliverbj . I am using `support`  for my `wink_path`. I have defined views and a controller for the blog. However, the package hijacks all requests to `/support` ignoring my defined controller. When I do, `/support/pages`, I get redirected to `/support/login`.
