### ISSUE TITLE
Can we have wink as part of application?

### ISSUE THREAD

**Issue by shirazsoft** [writingink/wink#224]
Hello,
I am working my application can I use wink as part of my application?

**Comment by Pluiesurlavitre** [comment]
It is written in the documentation:

> Wink runs on any Laravel application, it uses a separate database connection and authentication system so that you don't have to modify any of your project code.

So you can use it as part of your application.

**Comment by ahmedsliman** [comment]
In addition to what "Pluiesurlavitre" mentioned you can implement any of wink namespaces in any of you controller/model

Like `use Wink\WinkPost;`

Then use WinkPost, for instance, to view it into any part of your application.
