### ISSUE TITLE
When Session Driver is database, wink fails to login with exception.

### ISSUE THREAD

**Issue by caferelgin** [writingink/wink#229]
When session driver is set to database, login will cause exception due to user (author) id where the database table sessions will expect integer where wink author id is string. However, there is a workaround which is not very nice: I had to change wink_author id to integer to make it work.

**Comment by dancvrcek** [comment]
the same issue here - I can log in but each session update creates an exception - a bit of pain as we have error logs forward to a Slack channel.

I just wonder if changing the user_id to integer would cause collisions with the Laravel users. A separate session configuration would probably be better.

**Comment by dancvrcek** [comment]
ah - it looks like a good solution is to upgrade to the latest version 0.1, set a new middleware group

WINK_MIDDLEWARE_GROUP

and create a new definition without Sessions in the Kernel.php

**Comment by themsaid** [comment]
You'll need to adjust your session table to accept a UUID instead of an integer ID.

**Comment by OGhawsi** [comment]
For future comers: changing the user_id to type UUID on the session table, solved my problem.
