### ISSUE TITLE
Can't edit or delete a block.

### ISSUE THREAD

**Issue by euperia** [writingink/wink#232]
Firstly, this is a really good project.  Its enabled me to produce a basic CMS for a small site really quickly.

The problem I have is that I can't seen to be able to edit or delete a text/image/html block once it has been saved.  I can delete the block by highlighting it all and pressing delete, but that is unintuitive. 

Clicking in a text area doesn't appear to allow editing, or clicking on an uploaded image doesn't offer any UI to edit or delete it.

**Comment by dan-mesa** [comment]
Same issue here -- added HTML and there's no way to access it again. I can either delete it and re-add it, or edit it in the database.

**Comment by themsaid** [comment]
Fixed in V1. releasing soon :)
