### ISSUE TITLE
can't load image in server but local's fine 

### ISSUE THREAD

**Issue by adinugro88** [writingink/wink#233]
i have uploaded image but its not showing the image in server

**Comment by tvbeek** [comment]
Did you run `php artisan storage:link` on the server?

**Comment by adinugro88** [comment]
my server doesnt support php artisan

**Comment by tvbeek** [comment]
To make them accessible from the web, you should create a symbolic link from public/storage to storage/app/public
See: https://laravel.com/docs/6.x/filesystem#the-public-disk

If I'm correctly you can do `ln -s ../storage/app/public public/storage` in the root of your project. If that is not possible you need to have another way to let your webserver server storage/* from storage/app/public.
