### ISSUE TITLE
Ability to override Wink\WinkPost model

### ISSUE THREAD

**Issue by andruu** [writingink/wink#234]
Instead of hard coding WinkPost in the controllers can we have it pulled out of the service container so that it can be overridden.

My main reason is to add scout, but I'm sure a lot of other people would like to be able to modify/extend the model.

I'd be happy to work on this if this is something that makes sense.

**Comment by devcircus** [comment]
Yeah config options for all models would be nice.

**Comment by themsaid** [comment]
would happily merge a PR that adds this. Looking forward to it :) Thanks!
