### ISSUE TITLE
Laravel 7 Support Request 

### ISSUE THREAD

**Issue by Faisal50x** [writingink/wink#236]
Please Add laravel 7 support.

> Problem 1
    - Installation request for writingink/wink ^0.1.0 -> satisfiable by writingink/wink[v0.1].
    - Conclusion: remove laravel/framework v7.0.8
    - Conclusion: don't install laravel/framework v7.0.8
    - writingink/wink v0.1 requires laravel/framework ~5.7|~6.0 -> satisfiable by laravel/framework[5.7.x-dev, 5.8.x-dev, 6.x-dev].
    - Can only install one of: laravel/framework[5.7.x-dev, v7.0.8].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.0.8].
    - Can only install one of: laravel/framework[6.x-dev, v7.0.8].
    - Installation request for laravel/framework (locked at v7.0.8, required as ^7.0) -> satisfiable by laravel/framework[v7.0.8].

**Comment by themsaid** [comment]
fixed in v1.0
