### ISSUE TITLE
cpanel white screen on wink admin panel

### ISSUE THREAD

**Issue by mawans** [writingink/wink#237]
Hello sir/ma'am, 
my wink project works fine in localhost but on cpanel it displays white screen on wink admin panel. it displays posts from wink but on wink control panel, it has white screen more over the login screen also don't have any css, please help me ASAP
Thanks.

**Comment by MagedAhmad** [comment]
@mawans i faced the same issue but it works fine now .. 
in  `vendor/writingink/wink/resources/views/layout.php`

try to change from this
```
{{mix('app.js', 'vendor/wink')}}
```
to this
```
{{ url('vendor/wink/app.js') }}
```
