### ISSUE TITLE
I think wink does not really support Laravel 7

### ISSUE THREAD

**Issue by Mint-developer** [writingink/wink#238]
I have a fresh Laravel installation (version = 7.2.2). I am getting weird errors. I followed the steps mentioned in the documentation. The installation went well. When I go to project.test/wink I get this error. 
Symfony\Component\ErrorHandler\Error\FatalError
Trait 'Illuminate\Foundation\Auth\AuthenticatesUsers' not found

**_NOTE: Works fine with Laravel Version 6.18.2_**

Please help me with this. Thanks in advance.

**Comment by byjml** [comment]
In Laravel 7.x, the authentication scaffolding has been moved to laravel/ui.

```
composer require laravel/ui
```

**Comment by themsaid** [comment]
I'm removing the need to laravel/ui in v1.0. Releasing soon.
