### ISSUE TITLE
Forced Redirect to Login view

### ISSUE THREAD

**Issue by astr0naugh7** [writingink/wink#24]
BlogController.php in app/Http/Controllers

` <?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BlogController extends Controller
{
    //
    public function index()
	{
	    $posts = WinkPost::with('tags')
	        ->where('published', true)
	        ->where('publish_date', '<=', now()->toDateTimeString())
	        ->orderBy('publish_date', 'DESC')
	        ->simplePaginate(12);

	    return view('blog.index', [
	        'posts' => $posts
	    ]);
	}
}
`

Routes in app/routes/web.php
`Route::get('/blog', 											'BlogController@index')->name('blog.index');`

however, url.com/blog (which I'm making for my homepage) stills redirects instantly to url.com/blog/login ... am I missing a step?

**Comment by josepostiga** [comment]
Hi @astr0naugh7. 

It doesn't seem to be related to this controller.

Can you check if this Route declaration is inside a group with some kind of authentication middleware?

**Comment by astr0naugh7** [comment]
> Hi @astr0naugh7.
> 
> It doesn't seem to be related to this controller.
> 
> Can you check if this Route declaration is inside a group with some kind of authentication middleware?

It's all on it's own in the web.php routes. Not in any middleware.

**Comment by josepostiga** [comment]
Did you, by change, change the Wink config `path` variable to `blog`?

If so, try to change it to something else.

**Comment by astr0naugh7** [comment]
> No problem. Glad I could help

Class 'App\Http\Controllers\WinkPost' not found

Last thing, in the Blog Controller how do I get it to use the Wink* facade? use writingink\wink\WinkPost?

**Comment by josepostiga** [comment]
Yes, you have to add `use Wink\WinkPost` to your controller.

**Comment by astr0naugh7** [comment]
> Yes, you have to add `use Wink\WinkPost` to your controller.

Got it! Working nicely. Thank you!

**Comment by josepostiga** [comment]
You're welcome. Happy coding!
