### ISSUE TITLE
Saving avatar does not work with custom storage disk

### ISSUE THREAD

**Issue by alexrusin** [writingink/wink#29]
When defining disk like so:
```php 
'public_dev' => [
            'driver' => 'local',
            'root' => public_path('storage'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
```
and:
```bash
WINK_STORAGE_DISK=public_dev
```
leads to broken avatar image.  This is in part due to the way ImageUploadsController handles uploading image and returning path. 
The following change:
```php 
$path =  request()->image->store('/public/wink/images', config('wink.storage_disk'));
return response()->json([
            'url' => \Storage::disk(config('wink.storage_disk'))->url($path)
        ]);
```
Unfortunately this will lead to saving absolute url for avatar in the database, which is not desirable.  One way of dealing with the issue is to make ImageUploadsController save the avatar path in the database.  While doing so, it can also delete currently saved avatar from the disk. (Currently it is not deleting old avatar file when new one is uploaded).
Vue component should get avatar's absolute path, but this path should be generated on the server side by using Storage::url() function.  It will be also a good idea to make Vue generate default gravatar url if the path for avatar is empty (null), rather than saving default url for gravatar in the database.

**Comment by themsaid** [comment]
Hey,

Glad you figures it out, can you open a PR with a fix to the issue?

**Comment by alexrusin** [comment]
Sure. Will do that.

**Comment by themsaid** [comment]
fixed
