### ISSUE TITLE
[Road Map] Create an initial theme that people can use right away.

### ISSUE THREAD

**Issue by Lloople** [writingink/wink#30]
@themsaid I was thinking I can handle this feature of the Roadmap.

Before starting I would like to make a few questions:

- Would you like to have a route macro like `Route::winkDefault()`? Once the package is installed, you just would need to add that line to your route files to load the default theme routes
- Would it be correct to create a command like `php artisan wink:default-theme` or something like that to copy the assets (css mostly) to the `public` folder? There will be no need on copying views since that can be loaded from package folder. Some place like `public/vendor/wink/default.css`. Otherwise the `default.css` can be created on current `install` command.
- I'm not good at the design, so I was thinking of `copying` your current theme on themsaid.com for now (without the top bar, and routes inside `blog` just in case it's installed in a currently running app). Would that be appropriate? Simple & Minimal

**Comment by themsaid** [comment]
https://github.com/writingink/wink/pull/31

Closing this for now. Planning to do a fully publishable initial theme that people can use to build their own themes :)
