### ISSUE TITLE
Incompatible version conflict with flysystem-aws-s3-v3 

### ISSUE THREAD

**Issue by boonstoppel** [writingink/wink#307]
composer require league/flysystem-aws-s3-v3

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.0.2
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.0.1
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.0.0
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.0.0-RC1
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.0.0-beta.3
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.0.0-beta.2
    - league/flysystem-aws-s3-v3 2.0.0-alpha.4 requires league/flysystem 2.0.0-alpha.3 -> satisfiable by league/flysystem[2.0.0-alpha.3].
    - league/flysystem-aws-s3-v3 2.0.0-beta.1 requires league/flysystem 2.0.0-alpha.3 -> satisfiable by league/flysystem[2.0.0-alpha.3].
    - Conclusion: don't install league/flysystem 2.0.0-alpha.3
    - Installation request for laravel/framework (locked at v8.21.0, required as ^8.12) -> satisfiable by laravel/framework[v8.21.0].
    - league/flysystem-aws-s3-v3 2.0.0-alpha.1 requires league/flysystem 2.0.0-alpha.1 -> satisfiable by league/flysystem[2.0.0-alpha.1].
    - league/flysystem-aws-s3-v3 2.0.0-alpha.2 requires league/flysystem 2.0.0-alpha.1 -> satisfiable by league/flysystem[2.0.0-alpha.1].
    - Conclusion: don't install league/flysystem 2.0.0-alpha.1
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.x-dev|remove league/flysystem 1.1.3|install league/flysystem 2.0.0-alpha.1|install league/flysystem 2.0.0-alpha.3
    - Conclusion: don't install league/flysystem-aws-s3-v3 2.x-dev|don't install league/flysystem 1.1.3|install league/flysystem 2.0.0-alpha.1|install league/flysystem 2.0.0-alpha.3
    - Installation request for league/flysystem-aws-s3-v3 ^2.0 -> satisfiable by league/flysystem-aws-s3-v3[2.0.0, 2.0.0-RC1, 2.0.0-alpha.1, 2.0.0-alpha.2, 2.0.0-alpha.4, 2.0.0-beta.1, 2.0.0-beta.2, 2.0.0-beta.3, 2.0.1, 2.0.2, 2.x-dev].
    - league/flysystem-aws-s3-v3 2.x-dev requires league/flysystem ^2.0.0 -> satisfiable by league/flysystem[2.0.0, 2.0.0-RC1, 2.0.0-alpha.1, 2.0.0-alpha.2, 2.0.0-alpha.3, 2.0.0-alpha.4, 2.0.0-beta.1, 2.0.0-beta.2, 2.0.0-beta.3, 2.0.1, 2.0.2, 2.x-dev].
    - Can only install one of: league/flysystem[2.0.0, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-RC1, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-alpha.2, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-alpha.4, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-beta.1, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-beta.2, 1.1.3].
    - Can only install one of: league/flysystem[2.0.0-beta.3, 1.1.3].
    - Can only install one of: league/flysystem[2.0.1, 1.1.3].
    - Can only install one of: league/flysystem[2.0.2, 1.1.3].
    - Can only install one of: league/flysystem[2.x-dev, 1.1.3].
    - Installation request for league/flysystem (locked at 1.1.3) -> satisfiable by league/flysystem[1.1.3].

**Comment by tvbeek** [comment]
You can add a version to your version because now it tries to install a flysystem version2 while the project use a version 1.

With this command you pin it to version 1.

`composer require league/flysystem-aws-s3-v3:^1.0`
