### ISSUE TITLE
Preview Post

### ISSUE THREAD

**Issue by sammysmallman** [writingink/wink#308]
What set up is required to make 'Preview Post' return a preview of the post. From a pretty vanilla install I'm receiving a "404 — Post not found" even after publishing the post. Do you need to provide a view for a specific route for this to work?

**Comment by skino2019** [comment]
in your Wink Config theres a section to define it

`/*
    |--------------------------------------------------------------------------
    | Wink Post Preview Path
    |--------------------------------------------------------------------------
    |
    | Wink uses this path to display a preview link in the editor. While
    | building the link tag, the {postSlug} placeholder will be replaced
    | by the actual post slug.
    |
    */

    'preview_path' => '/{postSlug}',

    'editor' => [`

where you have /{postSlug i had to change mine to blog/{postSlug}

that gives you the preview.

**Comment by sammysmallman** [comment]
Ah! Thanks @skino2019, that pointed me in the right direction.
Then in the show method I should make sure I'm not filtering by live posts.
