### ISSUE TITLE
auto Login user

### ISSUE THREAD

**Issue by skino2019** [writingink/wink#314]
Ive seen a few posts but was wondering what the easiest way to "autologin" from a link. 

im putting together an application for a user who is lets say not too computer literate, so making this as user friendly as possible is important.

ive build everything else required just need to find a way to set it up so if once logged into the laravel App the user can click a link and automatically be logged into wink.

**Comment by Braunson** [comment]
@skino2019 You could use something like a magic link. See https://github.com/cesargb/laravel-magiclink but you'd have to integrate it into the system.
