### ISSUE TITLE
Creating a directory structure with slugs

### ISSUE THREAD

**Issue by joeh** [writingink/wink#316]
I am looking at using Wink to publish a bunch of content in our intranet.  But organizing content has me struggling.

Is there a way to create a directory structure using slugs.  For example, if I wanted to group a bunch of pages under a directory so rather than:

<<URL>>/about-us-our-management
<<URL>>/about-us-contact-us
<<URL>>/about-us-locations

we could have:
<<URL>>/about-us/our-management
<<URL>>/about-us/contact-us
<<URL>>/about-us/locations

Given the way the editor dynamically removes "/" characters from the slug name, the only way I can think to do this would be to do a custom route, or controller per "sub-directory".

Any other ideas?

Thanks

Joe

**Comment by themsaid** [comment]
No plans for this I'm afraid.
