### ISSUE TITLE
Customise CSS

### ISSUE THREAD

**Issue by skino2019** [writingink/wink#317]
Im trying to edit the default CSS that comes with Wink. ( i may be barking up the wrong tree with this ) I have built a dark website theme and no matter what i do i just cant seem to get my pages to display correctly...

default H2 tags are a gray colour but i want them white. and also hyperlinks are the same. 

![Image of Page](http://www.raspada-blog.co.uk/images/Sun-07-03-2021-1615125235.png)
![Image of Page2](http://www.raspada-blog.co.uk/images/Sun-07-03-2021-1615125323.png)

The hover colour works fine (the Pink).

Im using <p class="pb-6">{!! $post->body !!}</p> to display the info on the page. 

Is there a way to edit the default CSS for Wink?

**Comment by skino2019** [comment]
On another note. ive even tried the "insert HTML" option for the Hyperlink which allows the hover to show up pink but still the dark link when not being hovered

**Comment by themsaid** [comment]
I think it's because the content were pasted with styling. On DivingLaravel, both light and dark mode work as expected.
