### ISSUE TITLE
can't install wink

### ISSUE THREAD

**Issue by venixx04** [writingink/wink#319]
When I run the command  : composer require themsaid/wink, i get this message :   [InvalidArgumentException]
  Package themsaid/wink has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

PHP release : PHP 8.0.1 (cli)
Composer version : 2.0.8 2020-12-03 17:20:38

Thank

**Comment by ibrunotome** [comment]
`composer require themsaid/wink --ignore-platform-req=php`

Is the way until @themsaid needs php 8.

**Comment by tvbeek** [comment]
PHP 8 is currently supported 😄
