### ISSUE TITLE
PostgreSQL: operator does not exist: uuid = character varying 

### ISSUE THREAD

**Issue by josiasmontag** [writingink/wink#33]
When creating a new post with a PostgreSQL database I get the following error:

![image](https://user-images.githubusercontent.com/1945577/48351435-8d949380-e68a-11e8-92e4-86a5ebf0d599.png)

I think [author_id](https://github.com/writingink/wink/blob/master/src/Migrations/2018_10_30_000000_create_tables.php#L42) in wink_posts should be of type `uuid`, not of type string?

**Comment by themsaid** [comment]
thanks for the fix
