### ISSUE TITLE
Dates in Laravel 8

### ISSUE THREAD

**Issue by inmanturbo** [writingink/wink#330]
`Updated Invalid date — Created Invalid date`

This is due to the new timestamp formats I'd guess.
![wink](https://user-images.githubusercontent.com/47095624/120869250-036feb80-c564-11eb-8cef-01b5fea5e697.png)

**Comment by jersoncarin** [comment]
[wink-publishing](https://github.com/jersoncarin/wink-publishing) try this, this is forked of wink but fixed some known bugs

**Comment by themsaid** [comment]
Will look into this.
