### ISSUE TITLE
How can I use JetStream on Wink?

### ISSUE THREAD

**Issue by Hadi-pd** [writingink/wink#341]
I need to have more users with different roles on my site. I used **JetStream** to do this, but I don't know how I can match **JetStream** authentication with **Wink**?

**Comment by skino2019** [comment]
You can programmatically log them in. (i'm doing it with my blog.). i cant remember who helped me sort it out if he's reading reply so i can give credit where its due

[Gist - Programmatic Login](https://gist.github.com/skino2019/07b763a287d5dc4e936cc5b04720c7e7)

you just need to add the new column to your User DB  and that's it. works a charm.
