### ISSUE TITLE
Using wink in a multi user blogging laravel application

### ISSUE THREAD

**Issue by OfficialOzioma** [writingink/wink#342]
Hi, 
I came across this wonderful package and I will like to integrate it into my Laravel application.

I have a multi-user Laravel blog application, Just like medium, users are allowed to create accounts and create their own articles.

How can I config wink to allow multiple users to create accounts and also limit the menu options for a user

**For example** 
A user is not allowed to see teams on the menu.

**Comment by skino2019** [comment]
Ive not tried but i don't think there is functionality for this. I believe the Aim is to have this as a single team blogging platform.

**Comment by themsaid** [comment]
I'm afraid this is not something I want to introduce into Wink.
