### ISSUE TITLE
Latest Laravel 9 php 8.1

### ISSUE THREAD

**Issue by KDA809** [writingink/wink#353]
Will /wink be upgraded at any point? as its still using require php ^7.3||^7.4 so i cant use Wink on laravel 9 php 8.1

**Comment by lukeraymonddowning** [comment]
Any chance you could create a PR for it? 👌

**Comment by midnite81** [comment]
I've put in a pull request for this; https://github.com/themsaid/wink/pull/357

**Comment by KDA809** [comment]
Awesome @midnite81 🎉

**Comment by Braunson** [comment]
Also looking for this. By the looks of the PR, it seems the test suite needs to be adjusted first.
