### ISSUE TITLE
Unable to Install on Laravel 10 with PHP 8.1

### ISSUE THREAD

**Issue by skino2019** [writingink/wink#380]
I'm not sure if im missing something here but i cannot get Wink to install...

I'm running Laragon with PHP8.1 installed.

the version of Laravel I have in my Composer.Json is v10.9.0

When i run the:

`composer require themsaid/wink`

i get the following error:

```
 Problem 1
    - themsaid/wink[v0.0.1, ..., v0.2] require php ^7.1 -> your php version (8.1.10) does not satisfy that requirement.
    - themsaid/wink[v1.0, ..., v1.0.3] require php ^7.3 -> your php version (8.1.10) does not satisfy that requirement.
    - themsaid/wink[v1.1.0, ..., v1.2.0] require php ^7.3||^7.4 -> your php version (8.1.10) does not satisfy that requirement.
    - themsaid/wink[v1.2.1, ..., v1.3.1] require laravel/framework ^7.0||^8.0 -> found laravel/framework[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.8).
    - themsaid/wink v1.3.2 requires laravel/framework ^7.0||^8.0||^9.0 -> found laravel/framework[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.7] but it conflicts with your root composer.json require (^10.8).
    - Root composer.json requires themsaid/wink * -> satisfiable by themsaid/wink[v0.0.1, ..., v0.2, v1.0, ..., v1.3.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require themsaid/wink:*" to figure out if any version is installable, or "composer require themsaid/wink:^2.1" if you know which you need.
```

Any help would be amazing

Apologies if this has been answered elsewhere I couldn't find it.

**Comment by skino2019** [comment]
If i run the following command:

`composer require themsaid/wink --with-all-dependencies`

i get the same error

**Comment by skino2019** [comment]
Just noticed the Composer.json is missing a pipe seperator between version 9 and 10

its cuttently showing

```
    "require": {
        "php": "^7.3||^7.4||^8.0",
        "laravel/framework": "^7.0||^8.0||^9.0|^10.0"
```

and i believe it should be

```
    "require": {
        "php": "^7.3||^7.4||^8.0",
        "laravel/framework": "^7.0||^8.0||^9.0||^10.0"

```

never done PR's before so not sure how to do it lol.

**Comment by tvbeek** [comment]
Hello @skino2019 you can create a PR for the pipe 😉 

And besides that the support for Laravel 10 is merged but there isn't a new release created. That means you need to use dev-master to get it working 😃

**Comment by skino2019** [comment]
> Hello @skino2019 you can create a PR for the pipe 😉
> 
> And besides that the support for Laravel 10 is merged but there isn't a new release created. That means you need to use dev-master to get it working 😃

as you can probably guess im not great at all of this lol... I shall read up on PRs now lol

**Comment by skino2019** [comment]
This will be resolved once the new release is out.... Closing Issue 

Cheers @themsaid

**Comment by skino2019** [comment]
This will be resolved once the new release is out.... Closing Issue 

Cheers @themsaid
