### ISSUE TITLE
[Suggestion] Post Categories

### ISSUE THREAD

**Issue by RichToms** [writingink/wink#39]
I thought this would be a nice progression for this project, I'm typically finding that I want a category for a blog post and not just a list of tags 

I understand that tags can be used in it's place

**Comment by themsaid** [comment]
I think having tags is enough, you can assign one or many tags to your post :)

**Comment by Menelion** [comment]
@themsaid I'm new to Wink, so please bear with me. As for categories, they can be parts of fancy URLs like `my.blog/travel/trip-to-cyprus`, or: `my.blog/recipes/my-favorite-soup`, where `travel` and `recipes` are category slugs.

**Comment by Menelion** [comment]
@Lloople Sorry, but semantically tags are other thing than categories: category is something broad, like "travel", "gadgets", "clothing", "recipes"; tags, on the other part, are useful for searching, and one tag per post has kinda little sense.

**Comment by themsaid** [comment]
Ignore the wording, use tags as categories or as tags, wink isn’t enforcing how you do it 🙂

**Comment by alvarezskinner** [comment]
What i have done, is hardcoding in an array which are the tags i use as categories, and then in a foreach loop thru the tags, display as the category the first tag that is in that array and if not call it "general" category, not "pretty", requires you to be careful when adding tags, but its the only way i can think about, as i have several tags per post and then categories.

Seems like we have gotten to use to Wordpress and its categories and tags, i believe Ghost does the same as well? 😀

**Comment by devonzara** [comment]
I agree that tags are different than categories, but I don't think categories need to be implemented as a separate feature.

Instead, we could make use of the existing tag system by simply adding an `is_category` or `is_topic` boolean field to each tag; and for those who wish to nest them, you could add a `parent_id`. I think this would be a simple solution that doesn't bloat Wink but acts as a compromise for those who do wish to have that added capability.

**Comment by vimalmistry** [comment]
I like this package but I can not use because there is no category functionality.
Tag is fine. Let' me explain

I have blog I am posting things like 
news, snippets, tutorials etc => this are categories or we can say type. 
Tag like laravel ,vuejs ,react etc can be used in any post. but Type is only one for per post.
Post => belongs to one => Category/Type/OrList 
Post => many to many => Tags

**Comment by connecteev** [comment]
Agreed!
