### ISSUE TITLE
Slug out of title

### ISSUE THREAD

**Issue by ben182** [writingink/wink#4]
Would be a good idea to build the slug out of the title. Maybe with str_slug. Especially from an SEO standpoint its nice to have some speakable url and not something like example.com/draft-0bb06fa8-5165-4672-bbfc-030c15008b75.

**Comment by abr4xas** [comment]
Hi there @ben182 right now I'm working on this :)

**Comment by ben182** [comment]
Awesome

**Comment by Lloople** [comment]
@abr4xas Thanks for taking care of this feature! Could you please extend the Laravel's `str_slug` method in order to work with non-english words too? For example chaning ñ to n and ç to c. I always use this method for this kind of conversion:

```
function slugify($string, $replace = '-')
{
    $removeasci = iconv('UTF-8', 'ASCII//TRANSLIT', $string);
    $removecomas = str_replace('\'', '', $removeasci);
    $output = preg_replace('/[^a-zA-Z0-9]/', $replace, $removecomas);

    return strtolower($output);
}
```

**Comment by abr4xas** [comment]
Hey @Lloople sure... I have the same problem hahaha =P

**Comment by themsaid** [comment]
If the slug is empty, Wink will slugify the title you provide, but if the slug is filled we don't change it so you decide what to use :)

**Comment by ben182** [comment]
@themsaid It wont slugify the title but the slug itself if you fill the slug input

**Comment by themsaid** [comment]
Oh, I see. I'm just not sure if it's a good idea to update the slug if you change the title and override any existing value.

**Comment by ben182** [comment]
https://github.com/writingink/wink/blob/3aedd04c6c66de79a231987319986798243225d9/resources/js/screens/posts/edit.vue#L261

**Comment by ben182** [comment]
No you should not do this. Normally this should be set once and never changed

**Comment by abr4xas** [comment]
@themsaid what do think about use this package: https://github.com/spatie/laravel-sluggable

**Comment by ben182** [comment]
Yep exactly. This should be done on server side anyway.

**Comment by Lloople** [comment]
@themsaid What I think @ben182 is saying is:

- You create a post without filling the slug: the slug is generated using the post title
- You update a posts slug: the slug field gets slugified (changing spaces for `-` and that kind of things)
- You update a post and leave the slug empty: the slug is generated using the post title
- You update a post changing the title but not touching the slug: The slug remains untouched

**Comment by themsaid** [comment]
> You create a post without filling the slug: the slug is generated using the post title

By default a post has a blank title, that's why I use the ID instead.

**Comment by ben182** [comment]
Then the slug will only be saved when a title is set. Otherwise you can not publish

**Comment by Lloople** [comment]
@themsaid I don't think it's a good idea to fill the title with a default, I hink it's better to force the use to write a title, since it's a required field for a valid post 🤔. Or forcing you to change the slug `draft-{anything}` before publishing. I haven't tried the package yet so excuse me if something I say makes no sense 😅

**Comment by mallardduck** [comment]
> @themsaid I don't think it's a good idea to fill the title with a default, I think it's better to force the user to write a title since it's a required field for a valid post 🤔.

Agreed, I think that should just be a placeholder - not a preset default.

**Comment by themsaid** [comment]
I want you to be able to click on "New Post", start writing without thinking of title, slug, tags, just start writing, the post is auto saved for you.

When you want to publish you can look at the other stuff like Title, Slug, Tags, Featured Image, etc...

The whole point is to keep it at zero-resistance when it comes to writing, just write now and edit later.

**Comment by Lloople** [comment]
Yeah that sounds pretty good indeed 🤔 

Maybe a better approach would be to use a title like `Draft` with empty url, and not being able to publish a post if slug is empty and title is `Draft`

Since the slug will be modified on first touching of title, that wouldn't be a problem either. Once you write a post title, the slug gets updated. After saving, the slug won't be modified if you change the title again.

**Comment by themsaid** [comment]
@Lloople I'm fine with having an initial title as draft and slug as `draft-{uuid}` and prevent publishing if slug has `draft-{uuid}` format.

Do you think you can PR that?

**Comment by Lloople** [comment]
I’ll take a look this afternoon. As long as it’s backend code there’s no problem. Javascript is harder for me thought 😅

**Comment by themsaid** [comment]
I made it show a warning on publishing rather than "preventing". I'm not a big fan of preventing, the more choices the user is given the better :)

**Comment by Lloople** [comment]
👍 good! We still need to auto-generate the slug the first time the post title is changed thought 😅
