### ISSUE TITLE
Yarn upgraded version throws error when compiling

### ISSUE THREAD

**Issue by skoyah** [writingink/wink#56]
I had the yarn version 1.2.1 but when I upgraded it to the latest version It was unable to compile the assets due to an error with the node-sass. What I ended up doing was to delete the current `yarn.lock` file and run `yarn` and `yarn run dev` again. Everything is working fine now. How should we proceed to with the `yarn.lock` file now? Should we delete or commit a new `yarn.lock`?

**Comment by themsaid** [comment]
I don't see a problem on latest yarn.

**Comment by skoyah** [comment]
When I execute the `yarn` command I get this error:

![captura de ecra 2018-11-17 as 19 12 17](https://user-images.githubusercontent.com/36083448/48664289-bce93d00-ea9c-11e8-85db-5458df8540e8.png)

I'm not sure if it is an error only in my machine or if it is in general.

**Comment by themsaid** [comment]
I just did that and pushed. Thanks for the heads up :)
