### ISSUE TITLE
Hide password, remember_token from WinkAuthor model

### ISSUE THREAD

**Issue by bilias23** [writingink/wink#57]
Let me start with: This is the best blog package I have ever come across for Laravel, so a big thank you :slightly_smiling_face: 

I noticed that that the WinkAuthor model does not include something like

`protected $hidden = ['password', 'remember_token'];`

Is that on purpose? If not, it would be a good idea to add them in my opinion! I'd be more than happy to contribute.

**Comment by themsaid** [comment]
Yes please open a PR :)
