### ISSUE TITLE
Scopes for published and published_date

### ISSUE THREAD

**Issue by bilias23** [writingink/wink#58]
Given their extensive usage, it would be useful to add scopes regarding posts' `published`  and `published_date` fields. I was thinking something along those lines:

- `scopePublished()` and `scopeUnpublished()`

- `scopedBeforePublishedDate($date)` and `scopedAfterPublishedDate($date)`

Again, I 'd be more than happy to take care of those :slightly_smiling_face:

**Comment by themsaid** [comment]
Yes that makes sense, please go ahead and open a PR. thank you :)
