### ISSUE TITLE
Where can I find the default password for the user?

### ISSUE THREAD

**Issue by rajcoder7** [writingink/wink#7]
I followed all the steps and generated all the tables for wink in the wink db. The table author has a default user with email: admin@mail.com but I cannot get the password in plain text as it is already hashed. How can I know the password?

**Comment by ben182** [comment]
Actually it will be shown in clear text with the email after the installation. Otherwise you could do it quick and dirty by replacing the password in the db with a hash from here https://bcrypt-generator.com.

**Comment by themsaid** [comment]
@rajcoder7 as @ben182 explained, the password is displayed after you run the wink:migrate command.
