### ISSUE TITLE
Image upload storage path

### ISSUE THREAD

**Issue by iamsanjit** [writingink/wink#70]
When using public disk, it create public folder with in the app/public folder

![screenshot from 2018-11-18 13-22-52](https://user-images.githubusercontent.com/9400880/48676448-29177f80-eb35-11e8-97ef-eba922cc5f47.png)

I think the storage directory should be 'wink/images' instead of 'public/wink/images' in ImageUploadsContoller@upload

**Comment by themsaid** [comment]
Made this configurable via a `wink.storage_path` config attribute. Thanks :)
