### ISSUE TITLE
Could not open input file: artisan

### ISSUE THREAD

**Issue by HINW** [writingink/wink#71]
Getting "Could not open input file: artisan" after php artisan wink:install. I have other Laravel apps running well on same server so nothing wrong with the environment.

May you please update readme file? I cant figure out how to install your code. Looking forward to try out Wink.

Thank you in advance.

**Comment by iamsanjit** [comment]
It seems like you are missing artisan file.
- Make sure you are in the project root directory.
- You have artisan file available.
- and make sure you ran `composer install` before running `php artisan wink:install`

**Comment by HINW** [comment]
I follow install instructions as it stated in readme file. I'm in the project root - composer install, then php artisan wink:install - still gets "Could not open input file: artisan". What do I missing here?

**Comment by skoyah** [comment]
I think you are on the wrong directory. You need to run `php artisan wink:install` inside your laravel project folder. Are you running that command on your wink(package) folder?

**Comment by Manishfoodtechs** [comment]
I could not locate this laraval folder in answer. can anybody help me
