### ISSUE TITLE
Which key for unsplash integration

### ISSUE THREAD

**Issue by Sparclex** [writingink/wink#75]
Hi thanks for the great project.

I wanted to be able to use the unsplash integration but I am not sure which token I have to use. I saw in the code that I have to set the unsplash key in the services directory:
```php
// src/Wink.php line 15
'unsplash_key' => config('services.unsplash.key'),
```

But when I create an app on unsplash I only get two keys which both must be remain confidential
![image](https://user-images.githubusercontent.com/2805213/48694783-5f650580-ebee-11e8-978e-173d002dffdd.png)

I found out that the request works with the access key. But by exposing it to the frontend it is not confidential anymore. 

What would be the correct solution for that? _Or is the unsplash documentation just missleading?_

Thanks,

Silvan

**Comment by themsaid** [comment]
Use the Access Key for Wink, if you secure your wink installation no one will have access to the key except your team.
