### ISSUE TITLE
error while migration

### ISSUE THREAD

**Issue by ManojKiranA** [writingink/wink#76]
InvalidArgumentException  : Database [winkdb] not configured.

  at C:\xampp\htdocs\wink\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:140
    136|         // If the configuration doesn't exist, we'll throw an exception and bail.
    137|         $connections = $this->app['config']['database.connections'];
    138|
    139|         if (is_null($config = Arr::get($connections, $name))) {
  > 140|             throw new InvalidArgumentException("Database [{$name}] not configured.");
    141|         }
    142|
    143|         return $config;
    144|     }

  Exception trace:

  1   Illuminate\Database\DatabaseManager::configuration("winkdb")
      C:\xampp\htdocs\wink\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:103

  2   Illuminate\Database\DatabaseManager::makeConnection("winkdb")
      C:\xampp\htdocs\wink\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:74

  Please use the argument -v to see more details.

**Comment by Sparclex** [comment]
You need to set `WINK_DB_CONNECTION` in your env file. For example:
`WINK_DB_CONNECTION=mysql`
