### ISSUE TITLE
php artisan wink:migrate does nothing

### ISSUE THREAD

**Issue by javorszky** [writingink/wink#8]
As per instructions, running `php artisan wink:migrate` *should* give me default login credentials. However this is what happens for me:

```
21:14:55  javorszky@GaborrMBP  ~/Sites/wink  ⬡ v10.6.0  12s 
$ composer require writingink/wink
Using version ^0.0.1 for writingink/wink
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing writingink/wink (v0.0.1): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: writingink/wink
Package manifest generated successfully.

 21:15:25  javorszky@GaborrMBP  ~/Sites/wink  ⬡ v10.6.0  14s 
$ php artisan wink:install
Publishing Wink Assets...
Publishing Wink Configuration...
Wink was installed successfully.

 21:15:35  javorszky@GaborrMBP  ~/Sites/wink  ⬡ v10.6.0 
$ php artisan wink:migrate
Nothing to migrate.
```

To further complicate things, I haven't set up a different database connection for wink, but decided to reuse the one laravel uses (because why not...)

**Comment by ladhadha** [comment]
@themsaid yes the tables was created. But theres no initial user create. The steps that I run was. 
- I install fresh laravel app,
-  I add `writingink/wink` as dependency,
- I run `php artisan migrate` <-- I think this step that creating the tables, 
- I run `php artisan wink:install`,
- I run `php artisan wink:migrate`, the output was: `Nothing to migrate.`. Because I already run migration before.

Also I try to remove all, `wink_*` tables, and then run `php artisan wink:migrate`, but it gives me output:

```sh
Nothing to migrate.

   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wink.wink_authors' doesn't exist (SQL: insert into `wink_authors` (`id`, `name`, `slug`, `bio`, `email`, `password`, `updated_at`, `created_at`) values (cf3c3e5f-0849-47af-bd1d-16fa946d9d16, Regina Phalange, regina-phalange, This is me., admin@mail.com, $2y$10$N0xME7bPmDPkYP58kFiwweypBwyTnyMLXwKoeXNJ4xPJbOpJk3hCy, 2018-11-08 08:43:59, 2018-11-08 08:43:59))
```

Migration not running and no table was created. Already inspecting why the migration, it's because the migration file: `2018_10_30_`. I try to change the date to current date: Ex: `2018_11_08_`, then it works.

**Comment by javorszky** [comment]
It only has the laravel ones, but the tables for wink exist.

<img width="417" alt="screen shot 2018-11-08 at 08 48 46" src="https://user-images.githubusercontent.com/1196299/48187489-25188000-e333-11e8-96c3-436ee80956a0.png">

I've done it again, here are steps to reproduce from nothing:

1. `laravel new wink2`
2. `cd wink2`
3. `composer require writingink/wink`
4. create empty database, and edit `.env` file so laravel can do its own migrations
5. `php artisan migrate`, this migrates laravel tables
6. `php artisan wink:install`
7. add `WINK_DB_CONNECTION` to `.env` with the same value as `DB_CONNECTION`
8. `php artisan wink:migrate`
9. see "No migration needed"

Attached is a complete database dump

[laravel.wink2-2018-11-08-08-44-db.sql.gz](https://github.com/writingink/wink/files/2560967/laravel.wink2-2018-11-08-08-44-db.sql.gz)

**Comment by themsaid** [comment]
Guys you're running the installation steps wrong, don't run `php artisan migrate` but run `php artisan wink:migrate`

**Comment by ladhadha** [comment]
So for the fresh project, `php artisan migrate` should runned before adding `writingink/wink` as dependency, right? Or I just need to run `php artisan wink:migrate` at all?

**Comment by themsaid** [comment]
`php artisan wink:migrate` migrates wink tables and create an initial user. If you run the migrations before this command will not do anything since the tables already exist.

If you follow the installation steps as is it'll work .. composer require, wink:install, wink:migrate.

**Comment by javorszky** [comment]
Right, but what the installation steps do not say is that the installation expects a base laravel to be up and running already.

ie these needed to have been run _before_ doing the `composer require`:

1. `laravel new X`
2. set up creds
3. `php artisan migrate`
4. <time passes>
5. `composer require wink`, etc...

**Comment by nateritter** [comment]
I just ran into this same issue and I agree with @javorszky ... docs need to be updated to remove any assumptions that laravel migrate needs to be run.  That's not explicit (not implicit enough) in the current documentation to reduce confusion.
