### ISSUE TITLE
Pinned Posts [Help Wanted]

### ISSUE THREAD

**Issue by developing-sonder** [writingink/wink#87]
Pinned posts would add a layer of post sorting when retrieving and displaying posts. The functionality would work much like a Pinned Tweet where the pinned post would display first in any list of posts in which it was retrieved. 

**Feature Requirements:**

- Removed the Pinned Post from the WinkPost query results and place it at the top of the results collection without otherwise altering the order of the results. 
- Facilitate reordering via a Collection Marco
- Add a "Pin this Post" checkbox field to the General Settings Menu.
- Add an "is_pinned" tinyint field to the wink_posts table. 

**Questions Remaining**
1) Should we only allow one pinned post? If so, when one is ready to mark a post as pinned and a pinned post already exists, do we automatically remove the previous pin? Or, do we alert the user and show the previously pinned post's title with the option to continue or cancel the pin override? 

2) Should we allow multiple pins? If so, a Pinned Post view would be recommended for easier identification of pinned posts and easy unpinning. 

3) Should we include a "pin_until" datetime field on the wink_posts table that allows the author to pin their post until a specific time? 

4) Where to implement the Collection Marco? A service provider seems the appropriate place, but one would need to be added to the project and alter the installation instructions. Alternatively, it could be added directly to the WinkPost Model. 

I'd be happy to implement this feature after some guidance on what would be the best route to implementation.

**Comment by themsaid** [comment]
I was thinking of making it possible to add custom fields to Posts/Pages/Authors/Tags. Same way like in Nova where you can add a `is_pinned` checkbox, or a `is_featured` one.

Being able to add extra meta data to your entities will make it possible to add all kinds of features.

- Checkbox boolean values
- Text values
- <select>
- <select> multiple options

That way people can extend Wink in any way they want.

**Comment by developing-sonder** [comment]
I really like this idea. The ability to expand fields out on your own, and pull in field types via composer would be great. 

I would argue that a pinned or featured post is so undoubtably common that this custom field should be, at some point, provided out of the box.

**Comment by themsaid** [comment]
I think we'll stick to the custom fields thing since it'll be more flexible for different use cases. Hoping to introduce this sometime this month :)
