### ISSUE TITLE
Wink authentication routes are defaulting to my app routes

### ISSUE THREAD

**Issue by roni-estein** [writingink/wink#90]
This is a really awesome little package, learning a ton just source diving it. In the project I first went to test it out, when going to project.test/wink, it redirects to auth.login, and not wink.auth.login. Even though it looks like it should be using the wink pages. I haven't tried this on a fresh laravel app with no scaffolding yet.

when going to project.test/wink/login it does go to the wink login page. Perhaps it's not the intention, but wouldn't the expected behaviour be to redirect to the wink login when attempting to do something in the wink directory?

Cheers and thanks again.

**Comment by usamaejaz** [comment]
Same experience I am having.

**Comment by themsaid** [comment]
The middleware is redirecting to the wink login screen, I can't replicate this.

**Comment by roni-estein** [comment]
I’ll try re-installing it on a grab project when I get home tonight, and see if I can give you steps to re-produce this as it’s been a while since I played with this before.

**Comment by themsaid** [comment]
Closing for now.

**Comment by JhumanJ** [comment]
If anyone gets the same issue: look at you handle `AuthenticationException` in your Handler.php.

I added this to mine to fix this issue (which is not really one):
```php
/**
     * Convert an authentication exception into a response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Auth\AuthenticationException  $exception
     * @return \Illuminate\Http\Response
     */
    protected function unauthenticated($request, AuthenticationException $exception)
    {
        if (in_array('wink',$exception->guards())) {
            return redirect()->guest(url('/wink/login'));
        }

        ... (default handling)
    }
```
