### ISSUE TITLE
Use of AbstractWinkModel?

### ISSUE THREAD

**Issue by idragon81** [writingink/wink#91]
Any reason why we are extending all of the models with AbstractWinkModel?

From what I can see the only real use they are providing is overriding the DB Connection for Wink.

We can Reduce the WinkAuthor code by half by extending from Illuminate\Foundation\Auth\User, using AbstractWinkModel as a trait and removing all the redundant code.

I think this will help us keep the WinkAuthor model close to Laravel defaults

**Comment by themsaid** [comment]
Thanks for the suggestion, I'm doing some work in this area and will see if that still makes sense after I'm done.
