### ISSUE TITLE
Make Wink's Auth work with / defer to the parent project's Auth

### ISSUE THREAD

**Issue by connecteev** [writingink/wink#93]
The use-case: 
Suppose you have a complex Laravel webapp and want to add a blog to it. Your options are to use Wordpress or find something in Laravel like Wink (I strongly prefer a laravel solution, despite the strength of the Wordpress ecosystem of plugins and themes). 

Here's why the Auth piece is important:
1. You don't want to have 2 Auth systems (parent project and Wink)...you want your users to have ONE shared login system (that could either by email based and/or powered by Socialite for FB / Google / Linkedin / Github logins). This is huge for me because I want my users to be logged in in both places without having to create multiple accounts
2. As a developer I don't want to have to maintain 2 login systems (Auth of my main Laravel app, Wink's auth) that I have to sync constantly.

So, Making Wink's Auth work with / defer to the parent project's Auth would be a very common (and strong) use-case.

**Comment by themsaid** [comment]
This is already considered for Wink 1.0, will be looking into this soon.

Check https://github.com/writingink/wink/issues/13
