### ISSUE TITLE
Built in comments system

### ISSUE THREAD

**Issue by shreyanshpanchal** [writingink/wink#95]
Hello,
I'm thinking about sending a PR for built in comments system.
Is it okay to use a third party package `actuallymab/laravel-comment` to pull in comments functionality or do we want to implement it from the scratch?

**Comment by NathanHeffley** [comment]
What benefit would this provide over just developers installing that package themselves if they want comments?

**Comment by shreyanshpanchal** [comment]
They don't manually have to create views, validations, AJAX Actions, Route declaration etc..
In short they don't have to think about implementing it on their own.

Sorry i was just taking an opinion.
