### ISSUE TITLE
Can the editor of Wink be used as a seperate package?

### ISSUE THREAD

**Issue by GabMic** [writingink/wink#96]
I know that the editor uses Quill under the hood. 
But the modifications are looking very very good, and i was wondering if and how this can be used as a stand-alone package for laravel for projects with less needs that wink is offering solutions to them.
Thanks.

**Comment by themsaid** [comment]
I think this is possible, but no plans for it at the moment, maybe when the editor is more mature, still have plans for it :)

**Comment by GabMic** [comment]
Thanks man!
