### ISSUE TITLE
Feature Request: RSS Feed for posts (and tags)

### ISSUE THREAD

**Issue by rokde** [writingink/wink#97]
A blog should have a rss feed for its posts and maybe for the tags, so you can subscribe to a tag as reader.

@themsaid Do you have plans for this? Or do you want a PR for this feature? Then i can implement that for you.

**Comment by themsaid** [comment]
As @mallardduck mentions, it's outside the scope of the package, wink is just the dashboard for your content, it can include some helpers to help with the frontend but I don't see a sitemap or RSS feed are to be considered, there are tons of packages out there to help you with that.
