### ISSUE TITLE
Feature Request: Sitemap

### ISSUE THREAD

**Issue by rokde** [writingink/wink#98]
A website (or a part of it) should have a sitemap.

@themsaid Do you plan such a feature? Or do you prefer a PR for that? I can implement that, if you want to.

**Comment by themsaid** [comment]
As @mallardduck mentions, it's outside the scope of the package, wink is just the dashboard for your content, it can include some helpers to help with the frontend but I don't see a sitemap or RSS feed are to be considered, there are tons of packages out there to help you with that.
